FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Устанавливаем зависимости для PostgreSQL
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requiraraments.txt .
RUN python manage.py makemigrations main
RUN python manage.py migrate
RUN pip install --no-cache-dir -r requiraraments.txt

COPY . .

# Указываем, какой порт будет использовать приложение
EXPOSE 8010

# Команда для запуска приложения
CMD ["python", "manage.py", "runserver", "0.0.0.0:8010"]